name: dm4bem-env

channels:
  - conda-forge

dependencies:
  - python=3.8.8
  - ipywidgets=7.5.1
  - matplotlib=3.4.1
  - numpy=1.20.2
  - scipy=1.6.2
  - pandas=1.2.4

python -m spacy download en_core_web_sm
